name: Sync Hotfix to Homolog

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  create-sync-prs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pega todo o histórico do repositório

      - name: Fetch all branches
        run: |
          git fetch --all  # Garante que todas as branches remotas estejam disponíveis
          git checkout -B homolog origin/homolog || echo "Branch homolog já existe"

      - name: Check if commits from master are missing in homolog
        id: check_commits
        run: |
          # Conta commits reais da master que ainda não estão na homolog, ignorando merges
          missing_commits=$(git rev-list --no-merges --count homolog..master)

          if [[ "$missing_commits" -eq 0 ]]; then
            echo "No missing commits. Skipping PR creation."
            echo "create_pr=false" >> $GITHUB_ENV
          else
            echo "Missing commits detected. Proceeding with PR creation."
            echo "create_pr=true" >> $GITHUB_ENV
          fi

      - name: Create PR to Homolog
        if: env.create_pr == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: hotfix-to-homolog
          base: homolog
          title: "Sync hotfix from master to homolog"
          body: "Automated PR to sync hotfixes from master to homolog."
          labels: "automated,hotfix"
