name: Sync Hotfix to Homolog

on:
  push:
    branches:
      - master

jobs:
  create-sync-prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Fetch and Configure Git
        run: |
          git fetch --all --prune
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Marincor/EXEMPLO_SYNC_FORCE.git

      - name: Create Temporary Branch
        run: |
          # Cria uma nova branch a partir da master
          git checkout -b sync-hotfix-to-homolog
          git push origin sync-hotfix-to-homolog --force  # Força atualização remota

      - name: Create Sync PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: sync-hotfix-to-homolog  # Nova branch criada
          base: homolog
          title: "Sync hotfix from master to homolog"
          body: "Automated PR to sync hotfixes from master to homolog."
          labels: "automated,hotfix"
          reviewers: Marincor
          draft: false
          # Ignora verificações de diferença entre branches
          allow-empty-commits: true